#!/usr/bin/env python3
"""Flatten the Lucide icons named in tools/icons.txt into src/ui/icons/Icons.qml.

Icon.qml bakes the stroke colour into a data URI at runtime, so only the inner
geometry of each icon is kept; the outer <svg> element is re-emitted there.

Reads the ESM build of the `lucide` npm package. Point LUCIDE at an unpacked
copy of it:

    npm pack lucide && tar xzf lucide-*.tgz
    LUCIDE=package tools/gen-icons.py
"""
import os, pathlib, re, sys

root = pathlib.Path(__file__).resolve().parent.parent
icons = pathlib.Path(os.environ.get("LUCIDE", "")) / "dist" / "esm" / "icons"
if not icons.is_dir():
    sys.exit("set LUCIDE to an unpacked lucide npm package (dist/esm/icons)")
out = root / "src" / "ui" / "icons" / "Icons.qml"
names = [n for line in (root / "tools" / "icons.txt").read_text().splitlines()
         if not line.lstrip().startswith("#") for n in line.split()]

element = re.compile(r'\[\s*"(\w+)"\s*,\s*\{(.*?)\}\s*\]', re.S)
attribute = re.compile(r'"?([\w-]+)"?\s*:\s*"([^"]*)"')
shapes = {}
for name in sorted(set(names)):
    f = next((icons / f"{name}{ext}" for ext in (".mjs", ".js")
              if (icons / f"{name}{ext}").is_file()), None)
    if f is None:
        sys.exit(f"{name}: not in {icons}")
    parts = []
    for tag, attrs in element.findall(f.read_text()):
        pairs = " ".join(f'{k}="{v}"' for k, v in attribute.findall(attrs) if k != "key")
        parts.append(f"<{tag} {pairs} />")
    if not parts:
        sys.exit(f"{name}: no geometry found")
    shapes[name] = "".join(parts)

lines = ["pragma Singleton", "", "import QtQuick", "",
         "// Icon geometry, vendored from Lucide (ISC — see LICENSE.lucide beside this file).",
         "// Generated by tools/gen-icons.py from tools/icons.txt — do not hand-edit.",
         "QtObject {", "    readonly property var shapes: ({"]
items = list(shapes.items())
for i, (k, v) in enumerate(items):
    v = v.replace("'", "\\'")
    lines.append(f"        \"{k}\": '{v}'" + ("," if i < len(items) - 1 else ""))
lines += ["    })", "}", ""]
out.write_text("\n".join(lines))
print(f"wrote {out} ({len(shapes)} icons)")
